Repository harsh3dev/DevMatchups, pull requests merged in 2025-01, with the labels that each got.

#80 Fixes issue #72 (Text wrapping in footer)
  app/Footer/Footer.tsx
Labels: good first issue, SWOC, BEGINNER, Frontend

#75 Adding Development using Docker in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: SWOC, BEGINNER

#70 Add postgres to docker-compose.yml
  .env.example
  docker-compose.yml
Labels: SWOC, ADVANCE

#78 Update bento-grid.tsx
  components/magicui/bento-grid.tsx
Labels: SWOC, BEGINNER

#84 [FEAT] Added toast to find member page
  app/(dashboard)/(routes)/findmember/Form/Form.tsx
Labels: SWOC, INTERMEDIATE

#85 Sentry Setup
  .env.example
  .github/workflows/assign-issue.yml
  .github/workflows/label-prs.yml
  .github/workflows/sync-labels.js
  .gitignore
  app/(dashboard)/(routes)/findmember/Form/Form.tsx
  app/api/sentry-example-api/route.ts
  app/global-error.tsx
  app/sentry-example-page/page.tsx
  components/magicui/bento-grid.tsx
  instrumentation.ts
  next.config.mjs
  package-lock.json
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
Labels: SWOC, INTERMEDIATE

#110 fix update profile page
  Actions/login.ts
  app/api/user/route.ts
  app/dashboard/profile/EditProfileForm.tsx
  app/dashboard/profile/page.tsx
  lib/store/features/userSlice/userSlice.ts
Labels: SWOC, ADVANCE

#113 Changed Label: "resumeUrl" to "Website"
  app/dashboard/profile/page.tsx
Labels: SWOC, BEGINNER

#112 Replicate PR #85
  .env.example
  .github/workflows/assign-issue.yml
  .gitignore
  app/(dashboard)/(routes)/findmember/Form/Form.tsx
  app/api/sentry-example-api/route.ts
  app/global-error.tsx
  app/sentry-example-page/page.tsx
  components/magicui/bento-grid.tsx
  instrumentation.ts
  next.config.mjs
  package-lock.json
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
Labels: SWOC, INTERMEDIATE

#116 Made required changes
  app/(dashboard)/(routes)/findmember/Form/Form.tsx
Labels: SWOC, BEGINNER

#115 fixed
  app/dashboard/profile/EditProfileForm.tsx
Labels: SWOC, BEGINNER

#119 Hacker smkg/issue#101
  app/(dashboard)/layout.tsx
  app/dashboard/page.tsx
  package-lock.json
Labels: SWOC, INTERMEDIATE

#124 Replicated Pr#83
  .env.example
  app/layout.tsx
  components/Analytics.tsx
Labels: SWOC, ADVANCE

#123 Updated navbar FIX #120
  app/Footer/Footer.tsx
  app/Navbar/Navbar.tsx
Labels: SWOC, BEGINNER
